services:
  - type: web
    name: research-backend
    env: node
    plan: free
    rootDir: research_backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: storage-backend
    env: node
    plan: free
    rootDir: storage
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: chatbot
    env: node
    plan: free
    rootDir: chatbot
    buildCommand: npm install
    startCommand: npm start
